### ISSUE TITLE
Any plans to use fater-whisper?

### ISSUE THREAD

**Issue by dgoryeo** [Navodplayer1/speechlib#3]
Hi, thanks for the good work. SInce there was no placholder for discussion thread I am using this as a feature suggestion: whould you have any plans to use fater-whisper models --for the purpose reducing VRAM and processing time? Thanks.

**Comment by Navodplayer1** [comment]
Thanks for the suggestion. I may add this in future!

**Comment by Navodplayer1** [comment]
@dgoryeo added the faster-whisper. works like a charm!

**Comment by dgoryeo** [comment]
Wonderfull!!
Side question: can one specify large-v2 instead of large? I presume large will use large-v3, which unfortunately has bot been very good.
