### ISSUE TITLE
Add hhmmss or use audio file to form transcript file name.

### ISSUE THREAD

**Issue by gety9** [Navodplayer1/speechlib#9]
Currently output file has only ymd (output_2024-01-22.txt), meaning each transcript run on same day overwrites the previous. Is this desired behaviour? Don't think so.

transcript-2024-01-22-140515.txt will solve this

Or maybe use file name, example

audio_file > "DonaldTrumpSpeech2012.mp3"

transcript >  "DonaldTrumpSpeech2012.txt"

**Comment by Navodplayer1** [comment]
in latest release 1.0.11 solved this issue. file saved as filename_HHMMSS_language.txt
